have_fun: false
code_review:
  disable: false
  comment_severity_threshold: LOW
  max_review_comments: 50
  pull_request_opened:
    help: false
    summary: true
    code_review: true
ignore_patterns:
  - 'src/test/**'
